from langchain_groq import ChatGroq
from intervUAI.configs.prompts import CROSS_QUESTION_PROMPT
import logging

logging.basicConfig(level=logging.INFO,format="%(asctime)s - %(levelname)s - %(message)s")

def cross_question_node(state):
    logging.info("cross_question_node triggered")
    
    try:
        # Initialize LLM
        llm = ChatGroq(model="meta-llama/llama-4-maverick-17b-128e-instruct",temperature = 0.4)
        logging.info("LLM initialized successfully")
        state["memory"].append({"role": "user", "content": state['user_message']})

        # Format the prompt
        prompt = CROSS_QUESTION_PROMPT.format(
            memory = state['memory']
        )
        logging.info("Prompt formatted")

        # Get response from the model
        response = llm.invoke(prompt).content
        logging.info("Response generated by LLM")

        # Update memory
        state["memory"].append({"role": "assistant", "content": response})
        logging.info("State memory updated")

        return {**state, "ai_message": response}
    
    except Exception as e:
        logging.exception("Error in cross_question_node: %s", str(e))
        # Optional: Return state with error message
        return {**state, "ai_message": "Sorry, an error occurred while generating the question."}
